# # 使用Python 3.9作为基础镜像
# FROM python:3.9

# # 安装 pandas 库
# RUN apt-get install wget
# RUN pip install pandas sqlalchemy psycopg2

# # 设置工作目录为 /app
# WORKDIR /app

# # 将本地的 ingetst-data.py 文件复制到容器内的工作目录（/app）中
# COPY ingest-data.py ingest-data.py

# # ENTRYPOINT 指令实际上是在定义容器启动时要执行的主要命令；当容器启动时，会自动执行 python ingest-data.py 命令
# ENTRYPOINT ["python", "ingest-data.py"]

