name: 'your_project_name'
version: '1.0.0'
config-version: 2

profile: 'bigquery'  # 默认使用 BigQuery

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

models:
  your_project_name:
    bigquery:
      +materialized: table
      +schema: bigquery_models
    postgres:
      +materialized: table
      +schema: postgres_models