second_project:
  outputs:
    dev:
      dbname: airflow
      host: workfloworchestration-postgres-1
      pass: admin
      port: 5432
      schema: aiflow
      threads: 1
      type: postgres
      user: admin
  target: dev
trips_data_all:
  outputs:
    dev:
      dataset: staging
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /.google/credentials/google_credentials.json
      location: asia-east1
      method: service-account
      priority: interactive
      project: de-project-444809
      threads: 4
      type: bigquery
    prd:
      dataset: production
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /.google/credentials/google_credentials.json
      location: asia-east1
      method: service-account
      priority: interactive
      project: de-project-444809
      threads: 4
      type: bigquery
  target: dev
